/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CatsPage {
    }
    interface ExamplePage {
    }
    interface FirestoreXmplPage {
    }
    interface PostPage {
        "page": string;
    }
    interface TestPage {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCatsPageElement extends Components.CatsPage, HTMLStencilElement {
    }
    var HTMLCatsPageElement: {
        prototype: HTMLCatsPageElement;
        new (): HTMLCatsPageElement;
    };
    interface HTMLExamplePageElement extends Components.ExamplePage, HTMLStencilElement {
    }
    var HTMLExamplePageElement: {
        prototype: HTMLExamplePageElement;
        new (): HTMLExamplePageElement;
    };
    interface HTMLFirestoreXmplPageElement extends Components.FirestoreXmplPage, HTMLStencilElement {
    }
    var HTMLFirestoreXmplPageElement: {
        prototype: HTMLFirestoreXmplPageElement;
        new (): HTMLFirestoreXmplPageElement;
    };
    interface HTMLPostPageElement extends Components.PostPage, HTMLStencilElement {
    }
    var HTMLPostPageElement: {
        prototype: HTMLPostPageElement;
        new (): HTMLPostPageElement;
    };
    interface HTMLTestPageElement extends Components.TestPage, HTMLStencilElement {
    }
    var HTMLTestPageElement: {
        prototype: HTMLTestPageElement;
        new (): HTMLTestPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "cats-page": HTMLCatsPageElement;
        "example-page": HTMLExamplePageElement;
        "firestore-xmpl-page": HTMLFirestoreXmplPageElement;
        "post-page": HTMLPostPageElement;
        "test-page": HTMLTestPageElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CatsPage {
    }
    interface ExamplePage {
    }
    interface FirestoreXmplPage {
    }
    interface PostPage {
        "page"?: string;
    }
    interface TestPage {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "cats-page": CatsPage;
        "example-page": ExamplePage;
        "firestore-xmpl-page": FirestoreXmplPage;
        "post-page": PostPage;
        "test-page": TestPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cats-page": LocalJSX.CatsPage & JSXBase.HTMLAttributes<HTMLCatsPageElement>;
            "example-page": LocalJSX.ExamplePage & JSXBase.HTMLAttributes<HTMLExamplePageElement>;
            "firestore-xmpl-page": LocalJSX.FirestoreXmplPage & JSXBase.HTMLAttributes<HTMLFirestoreXmplPageElement>;
            "post-page": LocalJSX.PostPage & JSXBase.HTMLAttributes<HTMLPostPageElement>;
            "test-page": LocalJSX.TestPage & JSXBase.HTMLAttributes<HTMLTestPageElement>;
        }
    }
}
